theme: jekyll-theme-cayman

## Based on https://github.com/pietromenna/jekyll-cayman-theme/blob/master/_config.yml

# Setup
title:        "Thinking on artificial intelligence impact"
tagline:      "Phrases and thoughts regarding Artificial Intelligence and the impact it causes, or that affect opinions about it"
#baseurl:      ""

# About/contact
author:
  name:       Emerson Rocha
  url:        https://github.com/fititnt
